; Teste 3 - Testando alguns erros

EXTERN ; Uso de Extern Sem Begin, operando para o Extern
INPUT &OLD_DATA ; Erro lexicos
LOAD OLD_DATA
L1: L3: DIV TRES ; Erro Sintatico -> mais de um label
STORE  NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA , OLD_DATA
LOAD OLD_DATA
JMPP L2
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
