; Teste 1_3 - testando CONST negativo, hexadecimal, zero, positivo

SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS
STORE  NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA , OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 0x2
OLD_DATA: CONST -2
NEW_DATA: CONST 0
TMP_DATA: CONST 0XF

