; Teste 1_2 - Arquivo Modulo Mal Formatado, mas funcional

BIN1: BEGIN
EXTERN: BIN2 ; EXTERN com caracter ':'
EXTERN : OLD_DATA ; EXTERN com caracter ':' e espaçado
PUBLIC: L1 ; PUBLIC com caracter ':'
SECTION TEXT
JMP BIN2
L1: DIV dois ; minusculo
STORE  NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
sub     TMP_DATA ; minusculo
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA , OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 0x2 
NEW_DATA: SPACE
TMP_DATA: SPACE
end ; minusculo