SECTION TEXT
JMP BIN2 
L1: DIV DOIS 
STORE NEW_DATA 
MUL DOIS 
STORE TMP_DATA 
LOAD OLD_DATA 
SUB TMP_DATA 
STORE TMP_DATA 
OUTPUT TMP_DATA 
COPY NEW_DATA + 1 OLD_DATA 
LOAD OLD_DATA 
JMPP L1 
STOP 
DOIS: CONST 2 
NEW_DATA: SPACE 3 
TMP_DATA: SPACE
OLD_DATA: SPACE
BIN2: SPACE 